export const allCountries = [
  ' Buenos Aires ',
  'Catamarca ',
  'Chaco ',
  'Chubut ',
  'Córdoba ',
  'Corrientes ',
  'Entre Ríos - Paraná',
  'Formosa ',
  'Jujuy ',
  'La Pampa ',
  'La Rioja ',
  'Mendoza ',
  'Misiones ',
  'Neuquén ',
  'Río Negro ',
  'Salta ',
  'San Juan ',
  'San Luis ',
  'Santa Cruz ',
  'Santa Fe ',
  'Santiago del Estero ',
  'Tierra del Fuego, Antártida e Islas del Atlántico Sur ',
  'Tucumán '
]
